name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Create virtual environment
        run: |
          python -m venv .venv
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          source .venv/bin/activate
          pip install --upgrade pip
          pip install maturin pytest hypothesis tiktoken matplotlib

      - name: Build Python extension
        working-directory: python
        run: |
          source ../.venv/bin/activate
          maturin develop --release

      - name: Cargo tests
        run: cargo test --manifest-path rust/Cargo.toml --locked

      - name: Pytest suite
        working-directory: python
        run: |
          source ../.venv/bin/activate
          python -m pytest

      - name: Vendored tiktoken tests
        env:
          PYTHONPATH: python
        run: |
          source .venv/bin/activate
          python scripts/run_tiktoken_tests.py

      - name: Parity comparison script
        env:
          PYTHONPATH: python
        run: |
          source .venv/bin/activate
          python scripts/compare_with_tiktoken.py --json

      - name: Benchmark script smoke test
        env:
          PYTHONPATH: python
        run: |
          source .venv/bin/activate
          python scripts/benchmark_scaling.py --lengths 32 128 --batch-size 4 --output python/target/ci_benchmark.png
